#!/usr/bin/env bash
# v003-dynamic-rules-regression.sh
# v1.3.3 port: post-tool-use is the family's silent run-event-ledger consumer —
# it appends tool events (with file + boundary warnings) to the active run's
# events.jsonl and greps changed files for AI-slop markers; stdout stays EMPTY
# (the v0.x "RULE: <name>" rule-recommendation printing retired with the
# silent-stdout contract; rules still load at session start). Fails open when
# no run/rules state exists.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
HOOK="${PLUGIN_ROOT}/hooks/post-tool-use.sh"
STATE="${PLUGIN_ROOT}/scripts/state"

fail() { echo "FAIL: $1" >&2; exit 1; }

TMP="$(mktemp -d "${TMPDIR:-/tmp}/lazykimi-rules-test.XXXXXX")"
cleanup() { rm -rf "$TMP"; }
trap cleanup EXIT

# 1. Hook passes bash -n syntax check.
bash -n "$HOOK" || fail "post-tool-use.sh has syntax errors"

# 2. Seed a temp project with an active run.
CWD="$TMP" bash "$STATE/create-run.sh" rulestest "dynamic rules regression" >/dev/null \
  || fail "create-run failed"
EVENTS="$TMP/.lazykimi/runs/rulestest/events.jsonl"

cd "$TMP"

# 3. Write events append to the run ledger with the changed file recorded.
OUT1="$(mktemp)"
printf '{"hook_event_name":"PostToolUse","cwd":"%s","tool_name":"Write","tool_input":{"file_path":"%s/src/foo.ts"}}\n' "$TMP" "$TMP" \
  | bash "$HOOK" >"$OUT1" 2>&1 \
  || fail "hook exited non-zero on Write event"
[ -s "$OUT1" ] && fail "post-tool-use must stay silent on stdout, got: $(cat "$OUT1")"

python3 - "$EVENTS" "$TMP" <<'PYEOF'
import json, sys
events = [json.loads(line) for line in open(sys.argv[1]) if line.strip()]
tool_events = [e for e in events if e.get("tool") == "Write"]
assert tool_events, events
event = tool_events[-1]
assert event.get("files") == [f"{sys.argv[2]}/src/foo.ts"], event
assert "boundary_warning" in event, event  # product write outside .lazykimi/
PYEOF
echo "  [PASS] Write events append to the active run ledger with boundary warning"

# 4. AI-slop marker in the changed file is flagged in the ledger.
printf '// TODO(AI): generated by AI assistant\nexport const x = 1;\n' > "$TMP/src-slop.ts"
printf '{"hook_event_name":"PostToolUse","cwd":"%s","tool_name":"Write","tool_input":{"file_path":"%s/src-slop.ts"}}\n' "$TMP" "$TMP" \
  | bash "$HOOK" >/dev/null 2>&1 || fail "hook exited non-zero on slop grep"
grep -q '"ai_slop_comment"' "$EVENTS" || fail "AI-slop marker not recorded in the ledger"
mkdir -p "$TMP/src" 2>/dev/null || true
echo "  [PASS] AI-slop comment markers recorded"

# 5. With no active run, the hook still exits 0 silently (fail open).
OUT2="$(mktemp)"
printf '{"hook_event_name":"PostToolUse","cwd":"%s","tool_name":"Write","tool_input":{"file_path":"%s/src/foo.ts"}}\n' "$TMP/nonexistent" "$TMP/nonexistent" \
  | bash "$HOOK" >"$OUT2" 2>&1 \
  || fail "hook should fail open when no run state exists"
[ -s "$OUT2" ] && fail "hook printed output with no run state: $(cat "$OUT2")"
echo "  [PASS] fail-open with no run state"

echo "PASS: v003-dynamic-rules-regression (v1.3.3 semantics)"
